### ISSUE TITLE
Soil moisture

### ISSUE THREAD

**Issue by xanfus** [dongqi-DQ/WRF4PALM#14]
I've added lines into namelist file from configuration file produced by run_config_wrf4palm.py.
```
soil_moisture = 0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.307966467911417, 0.3100084575379103, 0.31236514789491227,
```
Execution (PALM) reports values around 0.57, thus moisture resets to 0.43 m3/m3 for soil-type=3 and warning is raised. I wonder if issue results from boussinesq approximation
```
approximation              = 'boussinesq',
```
Also, as one sees above, soil_moisture isn't set as list, so brackets could be omitted:
```
Add to your *_p3d file: 
 soil_moisture = [0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.30706168208206097, 0.307966467911417, 0.3100084575379103, 0.31236514789491227]
```

**Comment by dongqi-DQ** [comment]
PALM's land surface model checks the soil moisture automatically for each soil type at initialization. I'm guessing the high values of soil moisture are from the dynamic driver (so originally from WRF). The soil moisture in the PALM p3d namelist does not overwrite the soil moisture stored in the dynamic driver. 
This warning could be due to 
1. WRF and PALM use different parameterisation for soil types and moisture (so the soil moisture value at saturation for the soil type is different)
2. The land use in WRF does not match the one in PALM due to different sources and/or resolution of geospatial data

**Comment by xanfus** [comment]
Yes, soil gets increasingly moist approaching east boundary. Water reservoir is in this direction.
