### ISSUE TITLE
Runtime error when horizontal and vertical interpolation

### ISSUE THREAD

**Issue by J-Ssunn** [dongqi-DQ/WRF4PALM#24]

**Comment by dongqi-DQ** [comment]
I'm not sure why your `run_config_wrf4palm.py` would repeat reading WRF? After `Processing QVAPOR` etc., the script should be running the rest of data processing routines and create a netcdf dynamic driver for PALM. WRF4PALM shouldn't be reading WRF repeatedly. Can you elaborate further about that?

To help me diagnose this, can you show which line in Python returned the `zinterp is not accessed` message? And also where the `RuntimeError` was returned? 

Also, several things to check:
1. How much RAM did WRF4PALM cost? Interpolating from WRF to PALM sometimes can use a lot of RAM and the machine cannot handle
2. Are you using the latest commit of WRF4PALM? there may be some bugs in the previous versions and the latest version has been running okay

Can you also provide a sample of your WRF output (if possible) and the WRF4PALM namelist you used? So I can try to replicate what you did and can locate the issue.

**Comment by J-Ssunn** [comment]
1. RAM usage is up to approximately 1,800MB while running.

2. The script uses the latest v1.1.1.

Isn't zinterp not used in the script now? I don't think that's the cause.

I attached a file that extracted only a part of the time from my result file because upload size limit. That files also occur the same error.
And I attached a screenshot too. Hope we get the same result.

[wrf_output,namelist.zip](https://github.com/dongqi-DQ/WRF4PALM/files/11611810/wrf_output.namelist.zip)
![01](https://github.com/dongqi-DQ/WRF4PALM/assets/134999474/c418f916-0e02-40af-aa03-93299f0b5db5)
![02](https://github.com/dongqi-DQ/WRF4PALM/assets/134999474/9e97b2e1-7b7e-4d4a-bccc-832ce998be1a)

**Comment by dongqi-DQ** [comment]
Thanks for sharing the files. 

I tried to run WRF4PALM from scratch using your namelist and WRF file, but cannot replicate the error. I'm suspecting this might be due to 1) the Python environment, or 2) the inconsistency in the WRF4PALM code you have. 

For 1), I have a python environment yml file and the PALM dynamic driver created using your namelist and WRF output attached in [output.zip](https://github.com/dongqi-DQ/WRF4PALM/files/11619448/output.zip). Can you try to create a new virtual Python environment using the yml file with this command
```
conda env create -f wrf4palm_env_test.yml
```
And then run WRF4PALM in that environment:
```
conda activate wrf4palm
python run_config_wrf4palm.py namelist.wrf4palm
```

For 2) and also potentially `zinterp`, can you try to clone WRF4PALM (the latest commit) and start the programme from scratch? `zinterp` function is used to interpolate vertical levels from WRF and you can find it in `dynamic_util/process_wrf.py`. Therefore, it should exist and be used in WRF4PALM. 

One thing I noticed, which usually shouldn't be an issue, is that your operation system is Windows. You may want to try a Linux environment or Windows Subsystem for Linux (WSL), if the above doesn't work. We have been mainly using WRF4PALM in Linux machines, so we haven't had much test on Windows yet.

**Comment by J-Ssunn** [comment]
I successfully executed the script by setting it up in a new Linux environment. 
The tqdm process bar display option is abnormal, and I need to look at the results, but the result file is well generated. 
I will delete the issue's content because my problem is the configuration problem. 
Thanks for your help!
