### ISSUE TITLE
Offline nesting setting in _p3d file

### ISSUE THREAD

**Issue by aqianxiangkail** [dongqi-DQ/WRF4PALM#38]
Dear Dr. Lin,

hi, I am a beginner at using the palm model...... And now I encountered some problems when I used the dynamic driver generated by WRF4PALM in the way of offline nesting.  So could you give me some tips to set the nesting mode in _p3d files? and maybe have you experienced this error about "initial mixing ratio exceeds the saturation mixing ratio"? and how to resolve this problem? Thank you very very much for your assistance.

Thanks a lot and look forward to your reply.

Besti,
Qian

ERROR: 
 

                +++ error message from nest-id 01 ---
                    ID: PAC0199  generated by routine "dynamic_init_checks":
                    
                    initial mixing ratio exceeds the saturation mixing ratio, with rh =    105.101829797705      % at a height of    2902.50000000000      m for the first time (initial run)
                    
                    Further information can be found at
                    https://docs.palm-model.com/23.04/Reference/LES_Model/Logging/#PAC0199

            +++ error message from nest-id 01 ---
                    ID: NCF0537  generated by routine "get_variable_2d_real_dynamic":
                    
                    Problem reading attribute/variable - ls_forcing_right_u: NetCDF: Start+count exceeds dimension bound

**Comment by dongqi-DQ** [comment]
Hi there, 
I wonder whether this issue is completed or not? I do not have any nested simulation with offline nesting at the moment because our project hasn't touched that subject yet. 

I've seen similar errors reported from another user and our conclusion was that it is a PALM issue. 

Have you tried to run the simulation without your child domains? Does the simulation work? If the answers are both yes, then please turn to PALM ticket system for further help. 

Otherwise, feel free to send through your namelists and dynamic driver and I will give it a test. My timeline is a bit full at the moment, so please expect 2-3 weeks delay on the testing.

Thanks

**Comment by aqianxiangkail** [comment]
> Hi there, I wonder whether this issue is completed or not? I do not have any nested simulation with offline nesting at the moment because our project hasn't touched that subject yet.
> 
> I've seen similar errors reported from another user and our conclusion was that it is a PALM issue.
> 
> Have you tried to run the simulation without your child domains? Does the simulation work? If the answers are both yes, then please turn to PALM ticket system for further help.
> 
> Otherwise, feel free to send through your namelists and dynamic driver and I will give it a test. My timeline is a bit full at the moment, so please expect 2-3 weeks delay on the testing.
> 
> Thanks

Dear Dr. Lin,

Hi, the simulation without the child domain works well, and I have resolved these problems after I changed my domain size larger one. 

But now I am confused about the difference between offline nesting within the large-scale model (in website: ls_forcing_X_Y require &nesting_offl_parameters to be enabled to become effective) and the easy way only using dynamic files without &nesting_offl_parameters (the _p3d templates in PALM example cases presented no use of this command). 

I ran these two models and got little different results by comparing the av_profile, but in my mind, it should be the same because applied the same forcing data from the dynamic files, right? And have you run your program using &nesting_offl_parameters command to extract the forcing data from the dynamic driver?

Maybe when you are free could you please share your thoughts or insights on the matter?

Thanks a lot. Wish you have a nice weekends.

Besti,
Qian

**Comment by patikit** [comment]
Dear Qian,

do you already resolved your problems? Otherwise I might can help you.
Regarding the first issue: initial mixing ratio exceeds the saturation mixing ratio - you should increase your domain or alter the streching. I wonder, do you use the cloud model and what are your settings for humidity?

Regarding your question about getting slightly different results between these two approaches even when using the same forcing data from dynamic files, I can just make some assumptions because I never was aware of this, but good to know! Thanks for that: But I strongly encourage you to write a ticket for this issue.
While both approaches should theoretically produce similar results when provided with the same forcing data, there may be differences due to how the boundary conditions are handled or how the urban model interacts with the larger-scale atmospheric conditions in the offline nesting approach. Maybe you should have a deeper look into the source code?
Kind regards,
Patricia

**Comment by aqianxiangkail** [comment]
> Dear Qian,
> 
> do you already resolved your problems? Otherwise I might can help you. Regarding the first issue: initial mixing ratio exceeds the saturation mixing ratio - you should increase your domain or alter the streching. I wonder, do you use the cloud model and what are your settings for humidity?
> 
> Regarding your question about getting slightly different results between these two approaches even when using the same forcing data from dynamic files, I can just make some assumptions because I never was aware of this, but good to know! Thanks for that: But I strongly encourage you to write a ticket for this issue. While both approaches should theoretically produce similar results when provided with the same forcing data, there may be differences due to how the boundary conditions are handled or how the urban model interacts with the larger-scale atmospheric conditions in the offline nesting approach. Maybe you should have a deeper look into the source code? Kind regards, Patricia

Dear friends,

thanks for your advice. But the settings I used for the humidity only: 
    humidity             = .T.,
    q_surface            = 0.001,

And I have created many files with different domain sizes (from dx dy 40 to 200 or dz 60 to 100 and resolution from 10 to 50 ), this mixing ratio problem always occurred. Even when it is ok in the initial values, I will also get this warning message during the waring through the realistic checker.

 I don't know why. Maybe could you have another idea about it? 

Besti, 
Qian

**Comment by dongqi-DQ** [comment]
Hi Qian,

I think PALM automatically checks for the "unrealistic" water vapour mixing ratio, which can be turned off, but in any case, you'll get a warning. Why is this and how to avoid it? This is a question that you should ask the PALM developers or perhaps the ticket system already has someone who asked similar questions. 

This GitHub repo is for WRF4PALM issues and questions only. If you have further PALM questions, please open a ticket there and I'm sure the PALM developers are happy to help.

Cheers
